// packages/frontend-vue/src/App.vue
<template>
  <div id="app">
    <h1>Portfolio CRM - Vue</h1>
    <p>Vue frontend will be implemented in Phase 5</p>
  </div>
</template>

<script setup lang="ts">
// Placeholder - will be implemented in Phase 5
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// packages/frontend-react/src/App.tsx
function App() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-900">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
          Portfolio CRM - React
        </h1>
        <p className="text-gray-600 dark:text-gray-400">
          React frontend will be implemented in Phase 4
        </p>
      </div>
    </div>
  );
}

export default App;
